import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Données des tables (migration depuis tables.ts)
const tablesData = Array.from({ length: 24 }, (_, i) => ({
  name: `Table ${i + 1}`,
  capacity: 8, // Capacité par défaut de 8 personnes
  x: (i % 5) * 120 + 50,
  y: Math.floor(i / 5) * 120 + 50,
}));

// Données des invités (migration depuis guests.ts) - sans l'ID pour laisser l'auto-increment
const guestsData = [
  { name: "Margaux", tableId: 1 },
  { name: "Nathan", tableId: 1 },
  { name: "Manon", tableId: 1 },
  { name: "Pauline", tableId: 1 },
  { name: "Sarah", tableId: 1 },
  { name: "Eunice", tableId: 1 },
  { name: "Benly", tableId: 1 },
  { name: "Denise", tableId: 1 },
  { name: "Santos", tableId: 2 },
  { name: "Mamie", tableId: 2 },
  { name: "Teccy", tableId: 2 },
  { name: "Mailine", tableId: 2 },
  { name: "Maria", tableId: 2 },
  { name: "Fanny", tableId: 2 },
  { name: "Mari fanny", tableId: 2 },
  { name: "Papa teccy", tableId: 2 },
  { name: "Jafait", tableId: 3 },
  { name: "Naomi", tableId: 3 },
  { name: "Betty", tableId: 3 },
  { name: "Jonathan", tableId: 3 },
  { name: "Mina", tableId: 3 },
  { name: "Laeticia", tableId: 3 },
  { name: "Gina", tableId: 3 },
  { name: "Andrea", tableId: 3 },
  { name: "Aznath", tableId: 4 },
  { name: "Prescillia", tableId: 4 },
  { name: "Lea", tableId: 4 },
  { name: "Giresse", tableId: 4 },
  { name: "Domingos", tableId: 4 },
  { name: "Tante lydia", tableId: 4 },
  { name: "Jeff", tableId: 4 },
  { name: "Emilie", tableId: 4 },
  { name: "Patricia", tableId: 5 },
  { name: "Dieu merci", tableId: 5 },
  { name: "Grace", tableId: 5 },
  { name: "Lydie", tableId: 5 },
  { name: "Noelle", tableId: 5 },
  { name: "Agnes", tableId: 5 },
  { name: "Betty m", tableId: 5 },
  { name: "Mado", tableId: 5 },
  { name: "Sandra", tableId: 6 },
  { name: "Jessy", tableId: 6 },
  { name: "Michelle", tableId: 6 },
  { name: "Gloire", tableId: 6 },
  { name: "Rebecca", tableId: 6 },
  { name: "Marvin", tableId: 6 },
  { name: "Arlette", tableId: 6 },
  { name: "Esperanza", tableId: 6 },
  { name: "Tonton papi", tableId: 7 },
  { name: "Tata rachel", tableId: 7 },
  { name: "Nathan m", tableId: 7 },
  { name: "Femme papi", tableId: 7 },
  { name: "Maman rachel", tableId: 7 },
  { name: "Papa rachel", tableId: 7 },
  { name: "Kelly", tableId: 7 },
  { name: "Enfant kelly", tableId: 7 },
  { name: "Maggy", tableId: 8 },
  { name: "Arsene", tableId: 8 },
  { name: "Carine", tableId: 8 },
  { name: "Divine", tableId: 8 },
  { name: "Joel", tableId: 8 },
  { name: "Lydia c", tableId: 8 },
  { name: "Rebecca c", tableId: 8 },
  { name: "Merci", tableId: 8 },
  { name: "Lydia a", tableId: 9 },
  { name: "Jose", tableId: 9 },
  { name: "Naomi a", tableId: 9 },
  { name: "Belfore", tableId: 9 },
  { name: "Bernadette", tableId: 9 },
  { name: "Femme jose", tableId: 9 },
  { name: "Enfant jose", tableId: 9 },
  { name: "Rachel b", tableId: 9 },
  { name: "Papa", tableId: 10 },
  { name: "Maman", tableId: 10 },
  { name: "Rody", tableId: 10 },
  { name: "Asta", tableId: 10 },
  { name: "Mike", tableId: 10 },
  { name: "Jeorgia", tableId: 10 },
  { name: "Precilia r", tableId: 10 },
  { name: "Michelle r", tableId: 10 },
  { name: "Papa nathan", tableId: 11 },
  { name: "Maman nathan", tableId: 11 },
  { name: "David", tableId: 11 },
  { name: "Femme david", tableId: 11 },
  { name: "Enfant david", tableId: 11 },
  { name: "Junior n", tableId: 11 },
  { name: "Steve", tableId: 11 },
  { name: "Eden", tableId: 11 },
  { name: "Mamy rosette", tableId: 12 },
  { name: "Tata youseline", tableId: 12 },
  { name: "Emmanuel", tableId: 12 },
  { name: "Fauzia", tableId: 12 },
  { name: "Enfant fauzia", tableId: 12 },
  { name: "Enfant 2 fauzia", tableId: 12 },
  { name: "Arnold", tableId: 12 },
  { name: "Loyd", tableId: 12 },
  { name: "Grace k", tableId: 13 },
  { name: "Bebe grace", tableId: 13 },
  { name: "Josue", tableId: 13 },
  { name: "Enatha", tableId: 13 },
  { name: "Femme josue", tableId: 13 },
  { name: "Enfant josue", tableId: 13 },
  { name: "Rosette k", tableId: 13 },
  { name: "Mireille", tableId: 13 },
  { name: "Lydie p", tableId: 14 },
  { name: "Edith", tableId: 14 },
  { name: "Reine", tableId: 14 },
  { name: "Emmanuel p", tableId: 14 },
  { name: "Femme manu", tableId: 14 },
  { name: "Enfant manu", tableId: 14 },
  { name: "Enfant 2 manu", tableId: 14 },
  { name: "Mari reine", tableId: 14 },
  { name: "Philomene", tableId: 15 },
  { name: "Ezechiel", tableId: 15 },
  { name: "Genade", tableId: 15 },
  { name: "Femme ezechiel", tableId: 15 },
  { name: "Enfant ezechiel", tableId: 15 },
  { name: "Mari genade", tableId: 15 },
  { name: "Emmanuel m", tableId: 15 },
  { name: "Femme emmanuel", tableId: 15 },
  { name: "Paul malonda", tableId: 16 },
  { name: "Femme paul", tableId: 16 },
  { name: "Joel malonda", tableId: 16 },
  { name: "Femme joel", tableId: 16 },
  { name: "Enfant joel", tableId: 16 },
  { name: "Enfant 2 joel", tableId: 16 },
  { name: "Enfant 3 joel", tableId: 16 },
  { name: "Enfant 4 joel", tableId: 16 },
  { name: "Papa mamy", tableId: 17 },
  { name: "Mamy", tableId: 17 },
  { name: "Alda", tableId: 17 },
  { name: "Mari alda", tableId: 17 },
  { name: "Enfant alda", tableId: 17 },
  { name: "Sarah r", tableId: 17 },
  { name: "Mari sarah", tableId: 17 },
  { name: "Enfant sarah", tableId: 17 },
  { name: "Marlene", tableId: 18 },
  { name: "Flori", tableId: 18 },
  { name: "Abel", tableId: 18 },
  { name: "Mari marlene", tableId: 18 },
  { name: "Enfant marlene", tableId: 18 },
  { name: "Enfant 2 marlene", tableId: 18 },
  { name: "Mari flori", tableId: 18 },
  { name: "Enfant flori", tableId: 18 },
  { name: "Tonton alex", tableId: 19 },
  { name: "Tata alex", tableId: 19 },
  { name: "Grace alex", tableId: 19 },
  { name: "Dany", tableId: 19 },
  { name: "Femme dany", tableId: 19 },
  { name: "Enfant dany", tableId: 19 },
  { name: "Patrick", tableId: 19 },
  { name: "Femme patrick", tableId: 19 },
  { name: "Isidore", tableId: 20 },
  { name: "Femme isi", tableId: 20 },
  { name: "Enfant isi", tableId: 20 },
  { name: "Enfant 2 isi", tableId: 20 },
  { name: "Enfant 3 isi", tableId: 20 },
  { name: "Samuel", tableId: 20 },
  { name: "Femme samuel", tableId: 20 },
  { name: "Enfant samuel", tableId: 20 },
  { name: "Deni lubanza", tableId: 21 },
  { name: "Sarah lubanza", tableId: 21 },
  { name: "Enfant deni", tableId: 21 },
  { name: "Enfant 2 deni", tableId: 21 },
  { name: "Chouette", tableId: 21 },
  { name: "Grace lubanza", tableId: 21 },
  { name: "Pasteur", tableId: 22 },
  { name: "Femme pasteur", tableId: 22 },
  { name: "Femme isidore", tableId: 22 },
  { name: "Junior wele", tableId: 23 },
  { name: "Hugues lubanza", tableId: 23 },
  { name: "Monsieur kibanga", tableId: 23 },
  { name: "Madame kibanga", tableId: 23 },
  { name: "Yolande kwimi", tableId: 23 },
  { name: "Jr kwimi", tableId: 23 },
  { name: "Lys kwimi", tableId: 23 },
  { name: "Kwimi", tableId: 23 },
  { name: "Venus mafuta", tableId: 24 },
  { name: "Enfant venus", tableId: 24 },
  { name: "Wivine kwimi", tableId: 24 },
  { name: "Dorothée kwimi", tableId: 24 },
  { name: "Tonton Lykis", tableId: 24 },
  { name: "Lykis", tableId: 24 },
  { name: "Heritier kiaba", tableId: 24 },
  { name: "Kiaba", tableId: 24 },
];

async function main() {
  console.log("🌱 Début du seeding...");

  // Supprimer les données existantes
  await prisma.guest.deleteMany();
  await prisma.table.deleteMany();

  // Créer les tables
  console.log("📋 Création des tables...");
  await prisma.table.createMany({
    data: tablesData,
  });

  // Créer les invités
  console.log("👥 Création des invités...");
  await prisma.guest.createMany({
    data: guestsData,
  });

  console.log("✅ Seeding terminé!");
  console.log(`📊 ${tablesData.length} tables créées`);
  console.log(`👥 ${guestsData.length} invités créés`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
