import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Données des tables (migration depuis tables.ts)
const tablesData = Array.from({ length: 24 }, (_, i) => ({
  id: i + 1,
  name: `Table ${i + 1}`,
  x: (i % 5) * 120 + 50,
  y: Math.floor(i / 5) * 120 + 50,
}));

// Données des invités (migration depuis guests.ts)
const guestsData = [
  { id: 1, name: "Margaux", tableId: 1 },
  { id: 2, name: "Nathan", tableId: 1 },
  { id: 3, name: "Manon", tableId: 1 },
  { id: 4, name: "Pauline", tableId: 1 },
  { id: 5, name: "Sarah", tableId: 1 },
  { id: 6, name: "Eunice", tableId: 1 },
  { id: 7, name: "Benly", tableId: 1 },
  { id: 8, name: "Denise", tableId: 1 },
  { id: 9, name: "Santos", tableId: 2 },
  { id: 10, name: "Mamie", tableId: 2 },
  { id: 11, name: "Teccy", tableId: 2 },
  { id: 12, name: "Mailine", tableId: 2 },
  { id: 13, name: "Maria", tableId: 2 },
  { id: 14, name: "Fanny", tableId: 2 },
  { id: 15, name: "Mari fanny", tableId: 2 },
  { id: 16, name: "Papa teccy", tableId: 2 },
  { id: 17, name: "Jafait", tableId: 3 },
  { id: 18, name: "Naomi", tableId: 3 },
  { id: 19, name: "Betty", tableId: 3 },
  { id: 20, name: "Jonathan", tableId: 3 },
  { id: 21, name: "Mina", tableId: 3 },
  { id: 22, name: "Laeticia", tableId: 3 },
  { id: 23, name: "Gina", tableId: 3 },
  { id: 24, name: "Andrea", tableId: 3 },
  { id: 25, name: "Aznath", tableId: 4 },
  { id: 26, name: "Prescillia", tableId: 4 },
  { id: 27, name: "Lea", tableId: 4 },
  { id: 28, name: "Giresse", tableId: 4 },
  { id: 29, name: "Domingos", tableId: 4 },
  { id: 30, name: "Tante lydia", tableId: 4 },
  { id: 31, name: "Jeff", tableId: 4 },
  { id: 32, name: "Emilie", tableId: 4 },
  { id: 33, name: "Patricia", tableId: 5 },
  { id: 34, name: "Dieu merci", tableId: 5 },
  { id: 35, name: "Grace", tableId: 5 },
  { id: 36, name: "Lydie", tableId: 5 },
  { id: 37, name: "Noelle", tableId: 5 },
  { id: 38, name: "Agnes", tableId: 5 },
  { id: 39, name: "Betty m", tableId: 5 },
  { id: 40, name: "Mado", tableId: 5 },
  { id: 41, name: "Sandra", tableId: 6 },
  { id: 42, name: "Jessy", tableId: 6 },
  { id: 43, name: "Michelle", tableId: 6 },
  { id: 44, name: "Gloire", tableId: 6 },
  { id: 45, name: "Rebecca", tableId: 6 },
  { id: 46, name: "Marvin", tableId: 6 },
  { id: 47, name: "Arlette", tableId: 6 },
  { id: 48, name: "Esperanza", tableId: 6 },
  { id: 49, name: "Tonton papi", tableId: 7 },
  { id: 50, name: "Tata rachel", tableId: 7 },
  { id: 51, name: "Nathan m", tableId: 7 },
  { id: 52, name: "Femme papi", tableId: 7 },
  { id: 53, name: "Maman rachel", tableId: 7 },
  { id: 54, name: "Papa rachel", tableId: 7 },
  { id: 55, name: "Kelly", tableId: 7 },
  { id: 56, name: "Enfant kelly", tableId: 7 },
  { id: 57, name: "Maggy", tableId: 8 },
  { id: 58, name: "Arsene", tableId: 8 },
  { id: 59, name: "Carine", tableId: 8 },
  { id: 60, name: "Divine", tableId: 8 },
  { id: 61, name: "Joel", tableId: 8 },
  { id: 62, name: "Lydia c", tableId: 8 },
  { id: 63, name: "Rebecca c", tableId: 8 },
  { id: 64, name: "Merci", tableId: 8 },
  { id: 65, name: "Lydia a", tableId: 9 },
  { id: 66, name: "Jose", tableId: 9 },
  { id: 67, name: "Naomi a", tableId: 9 },
  { id: 68, name: "Belfore", tableId: 9 },
  { id: 69, name: "Bernadette", tableId: 9 },
  { id: 70, name: "Femme jose", tableId: 9 },
  { id: 71, name: "Enfant jose", tableId: 9 },
  { id: 72, name: "Rachel b", tableId: 9 },
  { id: 73, name: "Papa", tableId: 10 },
  { id: 74, name: "Maman", tableId: 10 },
  { id: 75, name: "Rody", tableId: 10 },
  { id: 76, name: "Asta", tableId: 10 },
  { id: 77, name: "Mike", tableId: 10 },
  { id: 78, name: "Jeorgia", tableId: 10 },
  { id: 79, name: "Precilia r", tableId: 10 },
  { id: 80, name: "Michelle r", tableId: 10 },
  { id: 81, name: "Papa nathan", tableId: 11 },
  { id: 82, name: "Maman nathan", tableId: 11 },
  { id: 83, name: "David", tableId: 11 },
  { id: 84, name: "Femme david", tableId: 11 },
  { id: 85, name: "Enfant david", tableId: 11 },
  { id: 86, name: "Junior n", tableId: 11 },
  { id: 87, name: "Steve", tableId: 11 },
  { id: 88, name: "Eden", tableId: 11 },
  { id: 89, name: "Mamy rosette", tableId: 12 },
  { id: 90, name: "Tata youseline", tableId: 12 },
  { id: 91, name: "Emmanuel", tableId: 12 },
  { id: 92, name: "Fauzia", tableId: 12 },
  { id: 93, name: "Enfant fauzia", tableId: 12 },
  { id: 94, name: "Enfant 2 fauzia", tableId: 12 },
  { id: 95, name: "Arnold", tableId: 12 },
  { id: 96, name: "Loyd", tableId: 12 },
  { id: 97, name: "Grace k", tableId: 13 },
  { id: 98, name: "Bebe grace", tableId: 13 },
  { id: 99, name: "Josue", tableId: 13 },
  { id: 100, name: "Enatha", tableId: 13 },
  { id: 101, name: "Femme josue", tableId: 13 },
  { id: 102, name: "Enfant josue", tableId: 13 },
  { id: 103, name: "Rosette k", tableId: 13 },
  { id: 104, name: "Mireille", tableId: 13 },
  { id: 105, name: "Lydie p", tableId: 14 },
  { id: 106, name: "Edith", tableId: 14 },
  { id: 107, name: "Reine", tableId: 14 },
  { id: 108, name: "Emmanuel p", tableId: 14 },
  { id: 109, name: "Femme manu", tableId: 14 },
  { id: 110, name: "Enfant manu", tableId: 14 },
  { id: 111, name: "Enfant 2 manu", tableId: 14 },
  { id: 112, name: "Mari reine", tableId: 14 },
  { id: 113, name: "Philomene", tableId: 15 },
  { id: 114, name: "Ezechiel", tableId: 15 },
  { id: 115, name: "Genade", tableId: 15 },
  { id: 116, name: "Femme ezechiel", tableId: 15 },
  { id: 117, name: "Enfant ezechiel", tableId: 15 },
  { id: 118, name: "Mari genade", tableId: 15 },
  { id: 119, name: "Emmanuel m", tableId: 15 },
  { id: 120, name: "Femme emmanuel", tableId: 15 },
  { id: 121, name: "Paul malonda", tableId: 16 },
  { id: 122, name: "Femme paul", tableId: 16 },
  { id: 123, name: "Joel malonda", tableId: 16 },
  { id: 124, name: "Femme joel", tableId: 16 },
  { id: 125, name: "Enfant joel", tableId: 16 },
  { id: 126, name: "Enfant 2 joel", tableId: 16 },
  { id: 127, name: "Enfant 3 joel", tableId: 16 },
  { id: 128, name: "Enfant 4 joel", tableId: 16 },
  { id: 129, name: "Papa mamy", tableId: 17 },
  { id: 130, name: "Mamy", tableId: 17 },
  { id: 131, name: "Alda", tableId: 17 },
  { id: 132, name: "Mari alda", tableId: 17 },
  { id: 133, name: "Enfant alda", tableId: 17 },
  { id: 134, name: "Sarah r", tableId: 17 },
  { id: 135, name: "Mari sarah", tableId: 17 },
  { id: 136, name: "Enfant sarah", tableId: 17 },
  { id: 137, name: "Marlene", tableId: 18 },
  { id: 138, name: "Flori", tableId: 18 },
  { id: 139, name: "Abel", tableId: 18 },
  { id: 140, name: "Mari marlene", tableId: 18 },
  { id: 141, name: "Enfant marlene", tableId: 18 },
  { id: 142, name: "Enfant 2 marlene", tableId: 18 },
  { id: 143, name: "Mari flori", tableId: 18 },
  { id: 144, name: "Enfant flori", tableId: 18 },
  { id: 145, name: "Tonton alex", tableId: 19 },
  { id: 146, name: "Tata alex", tableId: 19 },
  { id: 147, name: "Grace alex", tableId: 19 },
  { id: 148, name: "Dany", tableId: 19 },
  { id: 149, name: "Femme dany", tableId: 19 },
  { id: 150, name: "Enfant dany", tableId: 19 },
  { id: 151, name: "Patrick", tableId: 19 },
  { id: 152, name: "Femme patrick", tableId: 19 },
  { id: 153, name: "Isidore", tableId: 20 },
  { id: 154, name: "Femme isi", tableId: 20 },
  { id: 155, name: "Enfant isi", tableId: 20 },
  { id: 156, name: "Enfant 2 isi", tableId: 20 },
  { id: 157, name: "Enfant 3 isi", tableId: 20 },
  { id: 158, name: "Samuel", tableId: 20 },
  { id: 159, name: "Femme samuel", tableId: 20 },
  { id: 160, name: "Enfant samuel", tableId: 20 },
  { id: 161, name: "Deni lubanza", tableId: 21 },
  { id: 162, name: "Sarah lubanza", tableId: 21 },
  { id: 163, name: "Enfant deni", tableId: 21 },
  { id: 164, name: "Enfant 2 deni", tableId: 21 },
  { id: 165, name: "Chouette", tableId: 21 },
  { id: 166, name: "Grace lubanza", tableId: 21 },
  { id: 167, name: "Pasteur", tableId: 22 },
  { id: 168, name: "Femme pasteur", tableId: 22 },
  { id: 169, name: "Femme isidore", tableId: 22 },
  { id: 170, name: "Junior wele", tableId: 23 },
  { id: 171, name: "Hugues lubanza", tableId: 23 },
  { id: 172, name: "Monsieur kibanga", tableId: 23 },
  { id: 173, name: "Madame kibanga", tableId: 23 },
  { id: 174, name: "Yolande kwimi", tableId: 23 },
  { id: 175, name: "Jr kwimi", tableId: 23 },
  { id: 176, name: "Lys kwimi", tableId: 23 },
  { id: 177, name: "Kwimi", tableId: 23 },
  { id: 178, name: "Venus mafuta", tableId: 24 },
  { id: 179, name: "Enfant venus", tableId: 24 },
  { id: 180, name: "Wivine kwimi", tableId: 24 },
  { id: 181, name: "Dorothée kwimi", tableId: 24 },
  { id: 182, name: "Tonton Lykis", tableId: 24 },
  { id: 183, name: "Lykis", tableId: 24 },
  { id: 184, name: "Heritier kiaba", tableId: 24 },
  { id: 185, name: "Kiaba", tableId: 24 },
];

async function main() {
  console.log("🌱 Début du seeding...");

  // Supprimer les données existantes
  await prisma.guest.deleteMany();
  await prisma.table.deleteMany();

  // Créer les tables
  console.log("📋 Création des tables...");
  await prisma.table.createMany({
    data: tablesData,
  });

  // Créer les invités
  console.log("👥 Création des invités...");
  await prisma.guest.createMany({
    data: guestsData,
  });

  console.log("✅ Seeding terminé!");
  console.log(`📊 ${tablesData.length} tables créées`);
  console.log(`👥 ${guestsData.length} invités créés`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
